Pipeline and installer tweaks
arup-group/SpeckleInstaller pull request #4
Opened 2021-01-25 21:30 UTC by daviddekoning

Hi @peterjgrainger, this is a short PR that makes two changes:

1. the installer now checks the correct file for the Rhino/Grasshopper version (bug we inherited from the original installer)
2. the github action for creating a release now marks it as pre-release. This lets us test the artifact before it starts getting auto downloaded...

2021-01-25 21:36 UTC, peterjgrainger requested changes

2021-01-25 21:36 UTC, peterjgrainger commented on README.md
> +7. Check the created release, if all is well, press the `Edit` button and until the `Pre-release` checkbox
```suggestion
7. Download the installer and check the created release
8. If all is well, press the `Edit` button on the release, unselect the `This is a pre-release` checkbox and press `update release`
```

2021-01-25 22:48 UTC, daviddekoning commented on README.md
> +7. Check the created release, if all is well, press the `Edit` button and until the `Pre-release` checkbox
thanks, that's much clearer

2021-01-26 15:42 UTC, daviddekoning commented
@peterjgrainger any further concerns?

2021-01-26 15:43 UTC, peterjgrainger approved these changes

2021-01-26 15:43 UTC, peterjgrainger commented
Nope, all good 😁

2021-01-26 15:46 UTC, merged